packages:
  - "apps/*"
  - "packages/*"

overrides:
  '@hono/node-server': 1.19.13
  postcss: 8.5.20

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

onlyBuiltDependencies:
  - "@prisma/engines"
  - "esbuild"
  - "prisma"
  - "sharp"
